halaman face scanner
KHASs-Kharisma-Vidya-Seni/FrontEnd-Khavi pull request #16
Opened 2024-05-22 02:35 UTC by piu8

2024-05-22 02:47 UTC, ghifarikbar requested changes

2024-05-22 02:47 UTC, ghifarikbar commented on package.json
> +    "react-router-dom": "^6.23.1",
pakai versi ini aja `6.23.0`

2024-05-22 02:54 UTC, piu8 commented on package.json
> +    "react-router-dom": "^6.23.1",
kalo udah di ubah push lagi?

2024-05-24 15:50 UTC, ghifarikbar commented on package.json
> +    "react-router-dom": "^6.23.1",
iya betul

2024-05-28 14:10 UTC, tokimina commented on src/pages/Face-scanner.tsx
> +                <div className="RekomendasiGayaRambut font-['DM Serif Text'] text-5xl font-normal text-gray-800">
font dm-serif hapus

2024-05-28 14:11 UTC, tokimina commented on src/main.tsx
> +      <Route path="/face-scanner" element={<Face_scanner />} />
`<FaceScanner />`

2024-05-29 12:19 UTC, piu8 commented on package.json
> +    "react-router-dom": "^6.23.1",
install yarn nya atau gimana?

2024-05-30 12:37 UTC, ghifarikbar commented on package.json
> +    "react-router-dom": "^6.23.1",
yarn

2024-06-03 02:35 UTC, ghifarikbar commented on package.json
> +    "framer-motion": "^11.2.10",
framer nya pakai yang lama jangan diupdate

2024-06-03 02:35 UTC, ghifarikbar commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.2.2",
udah ada lucid react

2024-06-03 02:36 UTC, ghifarikbar requested changes

2024-06-03 02:36 UTC, ghifarikbar commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.2.2",
udah ada lucid react, pakai lucid react

2024-06-03 05:54 UTC, ghifarikbar commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.2.2",
karena 3 package bisa memberatkan project nya cukup pakai lucid-react karena udah intregrasi sama scandui

2024-06-03 10:57 UTC, ghifarikbar approved these changes

2024-06-03 10:57 UTC, merged