feat(auth-page): add new responsive auth-page
KHASs-Kharisma-Vidya-Seni/FrontEnd-Khavi pull request #5
Opened 2024-05-14 13:24 UTC by BilalShandyartaSyamsudin

### Yang udah selesai

- [x] Sudah responsive
- [x]  Sudah ada gambar
- [x] sudah ada warna

###  Yang belum selesai

- [ ] Belum ada animasi
- [ ] Belum ada hover

2024-05-14 17:43 UTC, buryne commented
Bilal @BilalShandyartaSyamsudin  ganti gambar kek gini file foto aman di figma req dari @ildakurnia 

![image](https://github.com/KHASs-Kharisma-Vidya-Seni/FrontEnd-Khavi/assets/108569380/b8d0d372-b194-4134-8faa-890e79d6c210)

2024-05-14 17:45 UTC, buryne commented on src/main.tsx
> +      <Route path="register" element={<Register />} />
About Ono Wae Ojo diHapus

2024-05-14 17:46 UTC, buryne commented on src/main.tsx
> +      <Route path="register" element={<Register />} />
@BilalShandyartaSyamsudin mau nganggo `git cz` ra?

2024-05-14 17:50 UTC, buryne commented
@BilalShandyartaSyamsudin  CC Secepatnya

2024-05-14 23:54 UTC, BilalShandyartaSyamsudin commented on src/main.tsx
> +      <Route path="register" element={<Register />} />
nganggo git cz

2024-05-15 06:35 UTC, buryne requested changes
Ganti path gambar ojo langsung akses disk D mu


CC @BilalShandyartaSyamsudin

2024-05-15 06:35 UTC, tokimina commented on src/main.tsx
> +      <Route index element={<Login />} />
Route Index Balikan ke Home, Login e buat path sendiri

2024-05-15 06:35 UTC, tokimina commented on src/Root.tsx
> +      <header>{/* <Navbar /> */}</header>
Aktifkan Navbar

2024-05-15 06:35 UTC, buryne commented on src/pages/Login.tsx
> +import backgroundImage from "D:/IL/FrontEnd-Khavi/src/assets/img/bg-login-15052024.png";
sing iki path e dibenerke ojo nganti disk D mu

2024-05-15 06:35 UTC, buryne commented on src/pages/Register.tsx
>  import backgroundRegister from "D:/IL/FrontEnd-Khavi/src/assets/img/BackgroundRegister.png";
iki barang path e dibenerke

2024-05-15 06:35 UTC, buryne commented on src/pages/Register.tsx
>  import backgroundRegister from "D:/IL/FrontEnd-Khavi/src/assets/img/BackgroundRegister.png";
path gambar e

2024-05-15 06:35 UTC, buryne commented on src/pages/Register.tsx
>  import RightRegister from "D:/IL/FrontEnd-Khavi/src/assets/img/rightregister.png";
iki path gambar

2024-05-15 06:37 UTC, BilalShandyartaSyamsudin commented on src/main.tsx
> +      <Route index element={<Login />} />
loh wes mau kok ganti neh

2024-05-15 06:38 UTC, BilalShandyartaSyamsudin commented on src/pages/Login.tsx
> +import backgroundImage from "D:/IL/FrontEnd-Khavi/src/assets/img/bg-login-15052024.png";
oh iyo ya wkwk

2024-05-15 07:00 UTC, buryne approved these changes

2024-05-15 07:00 UTC, merged